---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-zom

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft-zom
  name: minecraft-zom
  namespace: minecraft-zom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-zom
  template:
    metadata:
      labels:
        app: minecraft-zom
        name: minecraft-zom
    spec:
      containers:
        - name: minecraft-zom
          image: itzg/minecraft-server:java21
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "2"
              memory: "6Gi"
          ports:
          - name: minecraft-zom
            containerPort: 25565
            hostPort: 25566
            protocol: TCP
          env:
            - name: EULA
              value: "TRUE"
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: DIFFICULTY
              value: "easy" #peaceful, easy, normal, hard
            - name: ENABLE_RCON
              value: "false"
            - name: GENERATE_STRUCTURES
              value: "true"
            - name: MOTD
              value: "Minecraft Zombies!"
            - name: OPS
              value: "1490331b-e5fb-42fe-b292-6c7646ffd009"
            - name: WHITELIST
              value: "1490331b-e5fb-42fe-b292-6c7646ffd009"
              value: "4277ee50-92e5-4bfc-b52f-f8f0bc8c79d5"
            - name: ENABLE_WHITELIST
              value: "TRUE"
            - name: ONLINE_MODE
              value: "TRUE"
            - name: MAX-TICK-TIME
              value: "-1"
            - name: VIEW-DISTANCE
              value: "8"
                #- name: REMOVE_OLD_MODS
                # value: "TRUE"
            - name: TYPE
              value: "FORGE"
            - name: VERSION
              value: "1.20.1"
            - name: MEMORY
              value: ""
            - name: JVM_XX_OPTS
              value: "-XX:MaxRAMPercentage=75"
          volumeMounts:
          - name: minecraft-zom-data-world-volume
            mountPath: "/data/world"
          - name: minecraft-zom-data-mods-volume
            mountPath: "/data/mods"
          - name: minecraft-zom-data-modpacks-volume
            mountPath: "/data/modpacks"
      volumes:
      - name: minecraft-zom-data-world-volume
        hostPath:
         path: "/app/minecraft-zombies/data/world"
      - name: minecraft-zom-data-mods-volume
        hostPath:
         path: "/app/minecraft-zombies/data/mods"
      - name: minecraft-zom-data-modpacks-volume
        hostPath:
         path: "/app/minecraft-zombies/data/modpacks"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-zom
spec:
  selector:
    app: minecraft-zom
  ports:
    - port: 25566
      protocol: TCP
      targetPort: 25565
  externalIPs:
    - xxx.xxx.xxx.xxx
