---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-pixel

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft-pixel
  name: minecraft-pixel
  namespace: minecraft-pixel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-pixel
  template:
    metadata:
      labels:
        app: minecraft-pixel
        name: minecraft-pixel
    spec:
      containers:
        - name: minecraft-pixel
          image: itzg/minecraft-server:java8
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "4"
              memory: "6Gi"
            requests:
              cpu: "2"
              memory: "4Gi"
          ports:
          - name: minecraft-pixel
            containerPort: 25565
            hostPort: 25565
            protocol: TCP
          env:
            - name: EULA
              value: "TRUE"
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: DIFFICULTY
              value: "easy" #peaceful, easy, normal, hard
            - name: ENABLE_RCON
              value: "false"
            - name: GENERATE_STRUCTURES
              value: "true"
            - name: MOTD
              value: "Minecraft Pixelmon"
            - name: OPS
              value: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            - name: WHITELIST
              value: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            - name: ENABLE_WHITELIST
              value: "TRUE"
            - name: ONLINE_MODE
              value: "TRUE"
                #- name: REMOVE_OLD_MODS
                # value: "TRUE"
            - name: TYPE
              value: "FORGE"
            - name: VERSION
              value: "1.16.5"
            - name: MEMORY
              value: ""
            - name: JVM_XX_OPTS
              value: "-XX:+UseContainerSupport"
              value: "-XX:MaxRAMPercentage=75.0"
          volumeMounts:
          - name: minecraft-java-data-world-volume
            mountPath: "/data/world"
          - name: minecraft-java-data-mods-volume
            mountPath: "/data/mods"
          - name: minecraft-java-data-modpacks-volume
            mountPath: "/data/modpacks"
      volumes:
      - name: minecraft-java-data-world-volume
        hostPath:
         path: "/app/minecraft/data/world"
      - name: minecraft-java-data-mods-volume
        hostPath:
         path: "/app/minecraft/data/mods"
      - name: minecraft-java-data-modpacks-volume
        hostPath:
         path: "/app/minecraft/data/modpacks"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-pixel
spec:
  selector:
    app: minecraft-pixel
  ports:
    - port: 25565
      protocol: TCP
      targetPort: 25565
  externalIPs:
    - xxx.xxx.xxx.xxx
